/* Generated file do not edit */
#define DEVELHELP 1
#define CPU_FAM_NRF52 1
#define CPU_MODEL_NRF52840XXAA 1
#define CPU_CORE_CORTEX_M4F 1
// #define RIOT_APPLICATION "ocaml-freestanding"
// #define BOARD_NRF52840_MDK "nrf52840-mdk"
#define RIOT_BOARD BOARD_NRF52840_MDK
// #define CPU_NRF52 "nrf52"
#define RIOT_CPU CPU_NRF52
// #define MCU_NRF52 "nrf52"
#define RIOT_MCU MCU_NRF52
#define RIOT_VERSION "2021.10-devel-238-g024f4"
#define MODULE_AUTO_INIT 1
#define MODULE_AUTO_INIT_XTIMER 1
#define MODULE_BOARD 1
#define MODULE_CORE 1
#define MODULE_CORE_INIT 1
#define MODULE_CORE_MSG 1
#define MODULE_CORE_PANIC 1
#define MODULE_CORTEXM_COMMON 1
#define MODULE_CORTEXM_COMMON_PERIPH 1
#define MODULE_CORTEXM_FPU 1
#define MODULE_CPU 1
#define MODULE_CPU_COMMON 1
#define MODULE_DIV 1
#define MODULE_MALLOC_THREAD_SAFE 1
#define MODULE_MPU_STACK_GUARD 1
#define MODULE_NEWLIB 1
#define MODULE_NEWLIB_NANO 1
#define MODULE_NEWLIB_SYSCALLS_DEFAULT 1
#define MODULE_NRF52_VECTORS 1
#define MODULE_NRF5X_COMMON_PERIPH 1
#define MODULE_PERIPH 1
#define MODULE_PERIPH_COMMON 1
#define MODULE_PERIPH_GPIO 1
#define MODULE_PERIPH_INIT 1
#define MODULE_PERIPH_INIT_GPIO 1
#define MODULE_PERIPH_INIT_PM 1
#define MODULE_PERIPH_INIT_TIMER 1
#define MODULE_PERIPH_INIT_UART 1
#define MODULE_PERIPH_PM 1
#define MODULE_PERIPH_TIMER 1
#define MODULE_PERIPH_UART 1
#define MODULE_STDIO_UART 1
#define MODULE_SYS 1
#define MODULE_VDD_LC_FILTER_REG1 1
#define MODULE_XTIMER 1
